### PR TITLE
added the possibility of saving the extracted descriptors to an arbitrary directory

### PR DESCRIPTION
**Pull request by Enrico-Chiavassa**
added the possibility of saving the extracted descriptors to an arbitrary directory

### CODE REVIEW

**Comment by gmberton** [comment]
Hey this looks good! Can you just make two small changes:
1) I would just fix the path where descriptors are saved (i.e. removing the parameter descriptors_output_dir)

2) saving the features with numpy, like np.save("queries_descriptors.npy", queries_descriptors) and same for database.

And one question: why the change in [test_dataset.py](https://github.com/gmberton/VPR-methods-evaluation/pull/10/files#diff-310302d529d538657537c065e1642b9b54c87e45aba6747333306ce960013f08) ?

**Comment by Enrico-Chiavassa** [comment]
Hi, thanks for your inputs. I understand number 2 and I'll change it right away.
The change in test_dataset was an oversight, I'll fix it.

As for the first one, I found it useful to set an arbitrary output directory for the features. When I need to fetch them automatically, it is unclear how to best access the usual log directory, as it contains the timestamp which is not known precisely in advance.

**Comment by Enrico-Chiavassa** [comment]
I removed the --descriptors_output_dir argument

**Comment by gmberton** [comment]
Thank you!

**Pull request merged**
